/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Translate_bubbleIndexRouteImport } from './routes/translate_bubble/index'
import { Route as TranslateIndexRouteImport } from './routes/translate/index'
import { Route as Input_method_editorIndexRouteImport } from './routes/input_method_editor/index'
import { Route as TranslateSettingsRouteImport } from './routes/translate/settings'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Translate_bubbleIndexRoute = Translate_bubbleIndexRouteImport.update({
  id: '/translate_bubble/',
  path: '/translate_bubble/',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateIndexRoute = TranslateIndexRouteImport.update({
  id: '/translate/',
  path: '/translate/',
  getParentRoute: () => rootRouteImport,
} as any)
const Input_method_editorIndexRoute =
  Input_method_editorIndexRouteImport.update({
    id: '/input_method_editor/',
    path: '/input_method_editor/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TranslateSettingsRoute = TranslateSettingsRouteImport.update({
  id: '/translate/settings',
  path: '/translate/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/translate/settings': typeof TranslateSettingsRoute
  '/input_method_editor': typeof Input_method_editorIndexRoute
  '/translate': typeof TranslateIndexRoute
  '/translate_bubble': typeof Translate_bubbleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/translate/settings': typeof TranslateSettingsRoute
  '/input_method_editor': typeof Input_method_editorIndexRoute
  '/translate': typeof TranslateIndexRoute
  '/translate_bubble': typeof Translate_bubbleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/translate/settings': typeof TranslateSettingsRoute
  '/input_method_editor/': typeof Input_method_editorIndexRoute
  '/translate/': typeof TranslateIndexRoute
  '/translate_bubble/': typeof Translate_bubbleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/translate/settings'
    | '/input_method_editor'
    | '/translate'
    | '/translate_bubble'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/translate/settings'
    | '/input_method_editor'
    | '/translate'
    | '/translate_bubble'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/translate/settings'
    | '/input_method_editor/'
    | '/translate/'
    | '/translate_bubble/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  TranslateSettingsRoute: typeof TranslateSettingsRoute
  Input_method_editorIndexRoute: typeof Input_method_editorIndexRoute
  TranslateIndexRoute: typeof TranslateIndexRoute
  Translate_bubbleIndexRoute: typeof Translate_bubbleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate_bubble/': {
      id: '/translate_bubble/'
      path: '/translate_bubble'
      fullPath: '/translate_bubble'
      preLoaderRoute: typeof Translate_bubbleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/': {
      id: '/translate/'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input_method_editor/': {
      id: '/input_method_editor/'
      path: '/input_method_editor'
      fullPath: '/input_method_editor'
      preLoaderRoute: typeof Input_method_editorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/settings': {
      id: '/translate/settings'
      path: '/translate/settings'
      fullPath: '/translate/settings'
      preLoaderRoute: typeof TranslateSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  TranslateSettingsRoute: TranslateSettingsRoute,
  Input_method_editorIndexRoute: Input_method_editorIndexRoute,
  TranslateIndexRoute: TranslateIndexRoute,
  Translate_bubbleIndexRoute: Translate_bubbleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
